### PR TITLE
Mobile fixes

### PR DESCRIPTION
**Pull request by igala**
unmute fixes -G3-161

### CODE REVIEW

**Comment by igala** [comment]
g3-167

**Comment by amnonbb** [comment]
Your branch still has changes from workshop-question branch.

**Comment by igala** [comment]
what should I do??

I merged all changes from master to mobile fixes, I did not work with workshop-question branch.

I have no idea what is the resolution here

**Comment by igala** [comment]
and as I see the changes were made from mobile fixes to workshop-question and not from it as you noted.

**Pull request closed without merging**
